Remove 'assignee' and add 'assignees' field.
kgryte/github-create-issue pull request #2
Opened 2016-12-07 18:19 UTC by argonlaser

Signed-off-by: Venkata krishna Sundararajan <vkvenkat94@gmail.com>

2016-12-07 18:31 UTC, kgryte requested changes

2016-12-07 18:31 UTC, kgryte commented on bin/usage.txt
> +       --assignees uname1,uname2    Github usernames of assigned users.
Change to `user1,user2` to match README.

2016-12-07 18:31 UTC, kgryte commented on lib/data.js
> +* @param {String} [opts.assignees] - Github username of assigned users
s/username/usernames/

2016-12-07 18:31 UTC, kgryte commented on package.json
> +  "version": "2.0.0",
Don't bump the version. I do this on my end before publishing to ensure everything gets properly tagged, etc.

2016-12-07 18:31 UTC, kgryte commented on test/test.validate.js
> +		console.log(values[i])
Remove the `console.log`.

2016-12-07 18:31 UTC, kgryte commented on lib/data.js
> +		debug( 'Assigned user: %s', opts.assignees );
I would rather be explicit here.
```
debug( 'Assigned users: %s', opts.assignees.join( ',' ) );
```

2016-12-08 15:55 UTC, argonlaser commented on bin/usage.txt
> +       --assignees uname1,uname2    Github usernames of assigned users.
Done.

2016-12-08 15:55 UTC, argonlaser commented on package.json
> +  "version": "2.0.0",
Done.

2016-12-08 15:55 UTC, argonlaser commented on test/test.validate.js
> +		console.log(values[i])
Done.

2016-12-08 15:56 UTC, argonlaser commented on lib/data.js
> +		debug( 'Assigned user: %s', opts.assignees );
Done.

2016-12-08 15:58 UTC, argonlaser commented on lib/data.js
> +* @param {String} [opts.assignees] - Github username of assigned users
I have changed the param to ```{String[]}``` from ```{String}```. Correct me if its not what you meant.

2016-12-08 19:24 UTC, kgryte requested changes
Awesome! Only two more (JSDoc param type and making `username` plural) changes are needed before merging. Thanks!

2016-12-08 19:24 UTC, kgryte commented on lib/validate.js
> +* @param {String} [options.assignees] - Github username of assigned users
`@param {String[]}`

2016-12-08 19:24 UTC, kgryte commented on lib/validate.js
> +* @param {String} [options.assignees] - Github username of assigned users
Ah, and

> - Github usernames of assigned users

2016-12-09 13:47 UTC, argonlaser commented on lib/validate.js
> +* @param {String} [options.assignees] - Github username of assigned users
Oops. I missed that. Thanks for pointing.

2016-12-09 22:03 UTC, kgryte approved these changes

2016-12-09 22:04 UTC, merged